export const Produces = [
	{
		name: "rice irrigated",
		lowNitrogen: "5",
		lowPhosphorus: "1.5",
		lowPotassium: "1.5",
		mediumNitrogen: "2.5",
		mediumPhosphorus: "0.8",
		mediumPotassium: "0.8",
		highNitrogen: "1.3",
		highPhosphorus: "0.4",
		highPotassium: "0.4",
	},
	{
		name: "rice unirrigated",
		lowNitrogen: 3,
		lowPhosphorus: 1,
		lowPotassium: 1,
		mediumNitrogen: 1.5,
		mediumPhosphorus: 0.5,
		mediumPotassium: 0.5,
		highNitrogen: 0.8,
		highPhosphorus: 0.3,
		highPotassium: 0.3,
	},
	{
		name: "maize yearly",
		lowNitrogen: 3,
		lowPhosphorus: 1.5,
		lowPotassium: 1.5,
		mediumNitrogen: 1.5,
		mediumPhosphorus: 0.8,
		mediumPotassium: 0.8,
		highNitrogen: 0.8,
		highPhosphorus: 0.4,
		highPotassium: 0.4,
	},
	{
		name: "maize half yearly",
		lowNitrogen: 4.5,
		lowPhosphorus: 2.3,
		lowPotassium: 2.3,
		mediumNitrogen: 2.3,
		mediumPhosphorus: 1.1,
		mediumPotassium: 1.1,
		highNitrogen: 1.1,
		highPhosphorus: 0.6,
		highPotassium: 0.6,
	},
	{
		name: "wheat irrigated",
		lowNitrogen: 5,
		lowPhosphorus: 2.5,
		lowPotassium: 1.3,
		mediumNitrogen: 2.5,
		mediumPhosphorus: 1.3,
		mediumPotassium: 0.7,
		highNitrogen: 1.3,
		highPhosphorus: 0.6,
		highPotassium: 0.3,
	},
	{
		name: "wheat unirrigated",
		lowNitrogen: 2.5,
		lowPhosphorus: 2.5,
		lowPotassium: 1,
		mediumNitrogen: 1.3,
		mediumPhosphorus: 1.3,
		mediumPotassium: 0.5,
		highNitrogen: 0.6,
		highPhosphorus: 0.6,
		highPotassium: 0.3,
	},
	{
		name: "kodo unnat",
		lowNitrogen: 3,
		lowPhosphorus: 2,
		lowPotassium: 1.5,
		mediumNitrogen: 1.5,
		mediumPhosphorus: 1,
		mediumPotassium: 0.8,
		highNitrogen: 0.8,
		highPhosphorus: 0.5,
		highPotassium: 0.4,
	},
	{
		name: "sugarcane morahan",
		lowNitrogen: 6,
		lowPhosphorus: 3,
		lowPotassium: 2,
		mediumNitrogen: 3,
		mediumPhosphorus: 1.5,
		mediumPotassium: 1,
		highNitrogen: 1.5,
		highPhosphorus: 0.8,
		highPotassium: 0.5,
	},
	{
		name: "sugarcane khuti",
		lowNitrogen: 7.5,
		lowPhosphorus: 3,
		lowPotassium: 2,
		mediumNitrogen: 3.8,
		mediumPhosphorus: 1.5,
		mediumPotassium: 1,
		highNitrogen: 1.9,
		highPhosphorus: 0.8,
		highPotassium: 0.5,
	},
	{
		name: "tori rayo",
		lowNitrogen: 3,
		lowPhosphorus: 2,
		lowPotassium: 1,
		mediumNitrogen: 1.5,
		mediumPhosphorus: 1,
		mediumPotassium: 0.5,
		highNitrogen: 0.8,
		highPhosphorus: 0.5,
		highPotassium: 0.3,
	},
	{
		name: "barley, uwa",
		lowNitrogen: 2,
		lowPhosphorus: 2,
		lowPotassium: 1.5,
		mediumNitrogen: 1,
		mediumPhosphorus: 1,
		mediumPotassium: 0.8,
		highNitrogen: 0.5,
		highPhosphorus: 0.5,
		highPotassium: 0.4,
	},
	{
		name: "fapar",
		lowNitrogen: 1.5,
		lowPhosphorus: 1.5,
		lowPotassium: 1,
		mediumNitrogen: 0.8,
		mediumPhosphorus: 0.8,
		mediumPotassium: 0.5,
		highNitrogen: 0.4,
		highPhosphorus: 0.4,
		highPotassium: 0.3,
	},
	{
		name: "aduwa, alaichi",
		lowNitrogen: 2.5,
		lowPhosphorus: 1.5,
		lowPotassium: 2.5,
		mediumNitrogen: 1.3,
		mediumPhosphorus: 0.8,
		mediumPotassium: 1.3,
		highNitrogen: 0.6,
		highPhosphorus: 0.4,
		highPotassium: 0.6,
	},
	{
		name: "potato",
		lowNitrogen: 11,
		lowPhosphorus: 7,
		lowPotassium: 5,
		mediumNitrogen: 5.5,
		mediumPhosphorus: 3.5,
		mediumPotassium: 2.5,
		highNitrogen: 2.8,
		highPhosphorus: 1.8,
		highPotassium: 1.3,
	},
	{
		name: "tarkari bali, saagpaat jaat",
		lowNitrogen: 10,
		lowPhosphorus: 9,
		lowPotassium: 4,
		mediumNitrogen: 5,
		mediumPhosphorus: 4.5,
		mediumPotassium: 2,
		highNitrogen: 2.5,
		highPhosphorus: 2.3,
		highPotassium: 1,
	},
	{
		name: "tarkari bali, jarey jaat",
		lowNitrogen: 10,
		lowPhosphorus: 9,
		lowPotassium: 4,
		mediumNitrogen: 5,
		mediumPhosphorus: 4.5,
		mediumPotassium: 2,
		highNitrogen: 2.5,
		highPhosphorus: 2.3,
		highPotassium: 1,
	},
	{
		name: "green pea",
		lowNitrogen: 0.8,
		lowPhosphorus: 2,
		lowPotassium: 6,
		mediumNitrogen: 0.4,
		mediumPhosphorus: 1,
		mediumPotassium: 3,
		highNitrogen: 0.2,
		highPhosphorus: 0.5,
		highPotassium: 1.5,
	},
	{
		name: "cucumber",
		lowNitrogen: 7,
		lowPhosphorus: 2,
		lowPotassium: 5,
		mediumNitrogen: 3.5,
		mediumPhosphorus: 1,
		mediumPotassium: 2.5,
		highNitrogen: 1.8,
		highPhosphorus: 0.5,
		highPotassium: 1.3,
	},
	{
		name: "zuchhini",
		lowNitrogen: 12,
		lowPhosphorus: 9,
		lowPotassium: 3,
		mediumNitrogen: 6,
		mediumPhosphorus: 4.5,
		mediumPotassium: 1.5,
		highNitrogen: 3,
		highPhosphorus: 2.3,
		highPotassium: 0.8,
	},
	{
		name: "tomato srijana",
		lowNitrogen: 10,
		lowPhosphorus: 9,
		lowPotassium: 4,
		mediumNitrogen: 5,
		mediumPhosphorus: 4.5,
		mediumPotassium: 2,
		highNitrogen: 2.5,
		highPhosphorus: 2.3,
		highPotassium: 1,
	},
	{
		name: "tomato other",
		lowNitrogen: 10,
		lowPhosphorus: 10,
		lowPotassium: 7.5,
		mediumNitrogen: 5,
		mediumPhosphorus: 5,
		mediumPotassium: 3.8,
		highNitrogen: 2.5,
		highPhosphorus: 2.5,
		highPotassium: 1.9,
	},
	{
		name: "bhanta",
		lowNitrogen: 10,
		lowPhosphorus: 9,
		lowPotassium: 4,
		mediumNitrogen: 5,
		mediumPhosphorus: 4.5,
		mediumPotassium: 2,
		highNitrogen: 2.5,
		highPhosphorus: 2.3,
		highPotassium: 1,
	},
	{
		name: "ladyfinger",
		lowNitrogen: 10,
		lowPhosphorus: 9,
		lowPotassium: 3,
		mediumNitrogen: 5,
		mediumPhosphorus: 4.5,
		mediumPotassium: 1.5,
		highNitrogen: 2.5,
		highPhosphorus: 2.3,
		highPotassium: 0.8,
	},
	{
		name: "cauliflower local",
		lowNitrogen: 10,
		lowPhosphorus: 6,
		lowPotassium: 4,
		mediumNitrogen: 5,
		mediumPhosphorus: 3,
		mediumPotassium: 2,
		highNitrogen: 2.5,
		highPhosphorus: 1.5,
		highPotassium: 1,
	},
	{
		name: "cauliflower hybrid",
		lowNitrogen: 10,
		lowPhosphorus: 6,
		lowPotassium: 5,
		mediumNitrogen: 5,
		mediumPhosphorus: 3,
		mediumPotassium: 2.5,
		highNitrogen: 2.5,
		highPhosphorus: 1.5,
		highPotassium: 1.3,
	},
	{
		name: "cabbage",
		lowNitrogen: 12,
		lowPhosphorus: 9,
		lowPotassium: 4,
		mediumNitrogen: 6,
		mediumPhosphorus: 4.5,
		mediumPotassium: 2,
		highNitrogen: 3,
		highPhosphorus: 2.3,
		highPotassium: 1,
	},
	{
		name: "simi",
		lowNitrogen: 4,
		lowPhosphorus: 6,
		lowPotassium: 3,
		mediumNitrogen: 2,
		mediumPhosphorus: 3,
		mediumPotassium: 1.5,
		highNitrogen: 1,
		highPhosphorus: 1.5,
		highPotassium: 0.8,
	},
	{
		name: "bittergourd",
		lowNitrogen: 10,
		lowPhosphorus: 6,
		lowPotassium: 3,
		mediumNitrogen: 5,
		mediumPhosphorus: 3,
		mediumPotassium: 1.5,
		highNitrogen: 2.5,
		highPhosphorus: 1.5,
		highPotassium: 0.8,
	},
	{
		name: "taney bodi",
		lowNitrogen: 4,
		lowPhosphorus: 6,
		lowPotassium: 2,
		mediumNitrogen: 2,
		mediumPhosphorus: 3,
		mediumPotassium: 1,
		highNitrogen: 1,
		highPhosphorus: 1.5,
		highPotassium: 0.5,
	},
	{
		name: "bell pepper",
		lowNitrogen: 10,
		lowPhosphorus: 5,
		lowPotassium: 5,
		mediumNitrogen: 5,
		mediumPhosphorus: 2.5,
		mediumPotassium: 2.5,
		highNitrogen: 2.5,
		highPhosphorus: 1.3,
		highPotassium: 1.3,
	},
	{
		name: "onion",
		lowNitrogen: 12,
		lowPhosphorus: 9,
		lowPotassium: 4,
		mediumNitrogen: 6,
		mediumPhosphorus: 4.5,
		mediumPotassium: 2,
		highNitrogen: 3,
		highPhosphorus: 2.3,
		highPotassium: 1,
	},
];
